services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: chanze_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: chanze
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - chanze-network

  # Mongo Express (MongoDB Web UI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: chanze_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - chanze-network

  # MailPit (Development Email Server)
  mailpit:
    image: axllent/mailpit:latest
    container_name: chanze_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - chanze-network

  # FastAPI Backend 
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: chanze_backend
    restart: unless-stopped
    environment:
      # Database
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/chanze?authSource=admin
      
      # JWT Configuration
      SECRET_KEY: your-super-secret-key-change-in-production
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      
      # Email Configuration (MailHog)
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_TLS: false
      FROM_EMAIL: noreply@chanze.local
      
      # Application Settings
      APP_NAME: Task Management API
      FRONTEND_URL: http://localhost:3000
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
      - mailpit
    networks:
      - chanze-network
    # Fixed command - use uvicorn directly since dependencies are installed globally
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chanze_frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENVIRONMENT=development
      # Enable Vite HMR (Hot Module Replacement)
      - VITE_HMR_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - chanze-network
    stdin_open: true
    tty: true
volumes:
  mongodb_data:

networks:
  chanze-network:
    driver: bridge