version: "3.8"

services:
  studio:
    build:
      context: ..
      dockerfile: apps/studio/Dockerfile
      target: dev
    ports:
      - 8082:8082
  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:3.0.3
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3
  auth:
    environment:
      - GOTRUE_SMTP_USER=
      - GOTRUE_SMTP_PASS=
  meta:
    ports:
      - 5555:8080
  db:
    restart: 'no'
    volumes:
      # Use a separate dev data directory
      - ./volumes/db/dev-data:/var/lib/postgresql/data:Z
      - ./dev/data.sql:/docker-entrypoint-initdb.d/seed.sql
  storage:
    volumes:
      # Use a separate dev storage directory  
      - ./volumes/storage-dev:/var/lib/storage:z
